### PR TITLE
Adjusted to work with the actual version Yammer

### PR DESCRIPTION
**Pull request by iskigow**
New Version of Jasmine
Fix implementation
New struct

2017-02-24-173835_485x125_scrot

2017-02-24-175233_534x452_scrot

### CODE REVIEW

**Comment by mysticatea** [comment]
Oh, wow, thank you very much!
I will review and merge later.

**Comment by mysticatea** [comment]
I confirmed this is good working.
Thank you!

**Comment by iskigow** [comment]
Thank you for merged!

Could you let me know when you will upgrade the Chrome extension, please?!

And I think to build a Firefox extension too, or maybe use this over Greasemonkey and/or Tampermonkey.
What do you think?!

**Comment by mysticatea** [comment]
> Could you let me know when you will upgrade the Chrome extension, please?!

Sure, I'm waiting for Google distributes it :smiley: .

> And I think to build a Firefox extension too, or maybe use this over Greasemonkey and/or Tampermonkey.

I'll check for firefox extensions later.

**Comment by mysticatea** [comment]
It seems available on Chrome Web Store now.
It might be disabled since it requests new permission, accessing `https://*.assets-yammer.com/*`, in order to show avatar icons in popups.

**Pull request merged**
